### PR TITLE
PAHO Venezuela - Create single entry custom form and to add cascade complete and incomplete actions

### PR DESCRIPTION
**Pull request by xurxodev**
### :pushpin: References

closes https://app.clickup.com/t/nzdj09
https://app.clickup.com/t/ntem7q

### :memo: Implementation

I have created a new raw custom form without using the generator:
Reporte Semanal de Muestras - single entry

tasks:
- [x] Create a single entry data set 
- [x] Create a SQL view 
- [x] Create the custom form

Update 2021/08/25 :
- [x] Add cascade complete and incomplete actions

### :art: Screenshots

Captura de pantalla 2021-07-13 a las 12 58 21

### :fire: Is there anything the reviewer should know to test it?

This is the metadata necessary:
 - data set (single entry)
 - sql view
 - custom form

All metadata is included in this package
[PAHO-venezuela-metadata-single-entry.json.zip](https://github.com/EyeSeeTea/WHO-custom-forms/files/6808342/PAHO-venezuela-metadata-single-entry.json.zip)

Steps after import:

- Assign some Municipio level org units to 'Reporte Semanal de Muestras - single entry' dataset to test
- Create some establecimiento level org units to test
- Assign to 'Reporte Semanal de Muestras' data set the created establecimiento org units

### CODE REVIEW

**Review by ifoche — COMMENTED** [review]
@xurxodev I don't really see the action for cascade complete or incomplete. Could you guide me on how to execute it? This is what I can see, that seems like wrong:
screenshots_1631161215_0620_09092021_670x585

**Comment by xurxodev** [comment]
@nacho to test the last changes with the cascade complete feature the custom form in the PR must be upload manually, the scripts do not contain the last changes

**Review by ifoche — APPROVED** [review]
My bad, sorry @xurxodev. I was assuming that the metadata already contained the custom form, but I just guessed by coming from the honduras custom form that's actally not there and you need to explicitly modify the custom form. 

Looks fine in general. Thank you!

**Comment by ifoche** [comment]
and I see now your comment saying exactly that :)

**Pull request merged**
